import { TemplateBindingParseResult } from "@angular/compiler";

export const Localization = {
    station: "Station",
    machine: "Machine",
    inspectionReport: "Inspection Report",
    customerName: "Customer Name",
    erwSize: "ERW Size",
    erwJobOrderNo: "ERW Job order No.",
    specifications: "Specifications",
    cdwSize: "CDW Size",
    cdwJobOrderNo: "CDW Job order No.",
    quickEntry: "Quick Entry",
    report: "Report",
    activity: "Activity",
    entryTime: "Entry Time",
    collNo: "Coll No.",
    routCardNo: "Route CARD NO.",
    rolledQuantity: "Rolled Quantity",
    cgQuantity: "CG Quantity",
    submit: "SUBMIT",
    user: "User",
    guage: "Guage",
    equipment: "Equipment",
    erp: "ERP",
    download: "Download",
    analysis: " Analysis",
    submitForApproval: "Submit For Approval",
    reportTableArray: [
        {name: "Delivert 091", srNo: '0214', from: "Tushar L", to: "Aayush A", code: "300-19", noOfTubes: "1300"},
        {name: "Delivert 122", srNo: '0420', from: "Madhur G", to: "Kabir L", code: "300-19", noOfTubes: "1700", isDelivert: true},
        {name: "Delivert 130", srNo: '0476', from: "Resha K", to: "Shirsha B", code: "300-19", noOfTubes: "1200"},
        {name: "Delivert 133", srNo: '0501', from: "Harish S", to: "Bhaskar S", code: "300-19", noOfTubes: "723", isNotDelivert: true},
        {name: "Delivert 138", srNo: '0510', from: "Sneha M", to: "AAysh A", code: "300-19", noOfTubes: "1740", isDelivert: true},
    ],
    activityArray:[
        "Aaysh Molhotra has updated the workflow for IoT team. (@ 2:30 pm)",
        "Bhavani Molhotra has updated the workflow for IoT team. (@ 2:30 pm)",
        "Mehak Molhotra has updated the workflow for IoT team. (@ 2:30 pm)",
        "Gayanath Molhotra has updated the workflow for IoT team. (@ 2:30 pm)",
        "Shirsha Molhotra has updated the workflow for IoT team. (@ 2:30 pm)",
        "Shirsha Molhotra has updated the workflow for IoT team. (@ 2:30 pm)",
        "Shirsha Molhotra has updated the workflow for IoT team. (@ 2:30 pm)",
        "Shirsha Molhotra has updated the workflow for IoT team. (@ 2:30 pm)",
        "Shirsha Molhotra has updated the workflow for IoT team. (@ 2:30 pm)",
        "Shirsha Molhotra has updated the workflow for IoT team. (@ 2:30 pm)",
    ],
    rejected:"Rejected",
    approved: "Approved",
    pendingForApproval: "Pending For Approval"
}